export const LOADED = 'todos/loaded'
export const ADD_TODOS = 'todos/added'
export const DELETE_TODOS = 'todos/deleted'
export const TOGGLED = 'todos/toggled'
export const COLOR_SELECTED = 'todos/colorSelected'
export const ALL_COMPLETED = 'todos/allCompleted'
export const CLEAR_COMPLETED = 'todos/clearCompleted'
